#ifndef _{up_classname}_H_
#define _{up_classname}_H_

/* THIS CLASS HAS BEEN AUTO GENERATED BY THE generate_class.py SCRIPT */

/**
 * Class {classname} :
 * TODO: Describe your class here
 */
class {classname} {{
	private:
{attributes}
	public:
		{classname}();
		{classname}(const {classname}& other);
		{classname}({classname}&& other);
		{classname}& operator=({classname} other);
		~{classname}();
		
		/**
		 * swap the two objects
		 */
		friend void swap({classname}& first, {classname}& second);

		/* In place operators */
{ioperators_def}
}}

/* Binary operators*/
{operators_def}

#endif // _{up_classname}_H_

